apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp-deployment
spec:
  selector:
    matchLabels:
      app: mynodeapp
  replicas: 2
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: devsupanut/nodejs-demo:1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000